#!/usr/bin/env python3
"""Plot the validation line profile produced by analytic_wire_test.

This script reads the CSV written to ``outputs/validation_wire_line.csv`` and
produces a simple plot of magnetic flux density magnitude along the horizontal
centerline. In addition to the numerical profile it overlays the analytic
expectation for a finite-radius conductor (``B ∝ r`` inside the core and ``B ∝
1/r`` outside). The apparent dip to zero in the centre of the plot is therefore
expected: the magnetic field magnitude is zero at the very centre of a solid
wire carrying uniform current.

The script requires ``numpy`` and ``matplotlib``. Usage::

    python -m pip install numpy matplotlib
    python python/visualize_wire.py

The plot is displayed on screen and optionally saved as PNG when ``--save`` is
provided.
"""

from __future__ import annotations

import argparse
import csv
import pathlib
from typing import List

import matplotlib.pyplot as plt
import numpy as np


def read_profile(path: pathlib.Path) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    """Load x, y, and magnitude columns from a CSV file."""

    xs: List[float] = []
    ys: List[float] = []
    vals: List[float] = []

    with path.open("r", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        for row in reader:
            xs.append(float(row["x"]))
            ys.append(float(row["y"]))
            vals.append(float(row["value"]))

    return np.asarray(xs), np.asarray(ys), np.asarray(vals)


def analytic_wire_profile(xs: np.ndarray, mu0: float, current: float, rc: float) -> np.ndarray:
    """Return the analytic |B| along a horizontal line for a finite-radius wire."""

    rs = np.abs(xs)
    b = np.empty_like(rs)
    inside = rs <= rc
    outside = ~inside

    # Inside the conductor: B = mu0 * I * r / (2*pi*rc^2)
    b[inside] = mu0 * current * rs[inside] / (2.0 * np.pi * rc * rc)

    # Outside the conductor: B = mu0 * I / (2*pi*r)
    b[outside] = mu0 * current / (2.0 * np.pi * rs[outside])
    return b


def plot_profile(
    xs: np.ndarray,
    vals: np.ndarray,
    mu0: float,
    current: float,
    rc: float,
    save: pathlib.Path | None,
) -> None:
    """Display the B-field magnitude profile and optionally save to disk."""

    fig, ax = plt.subplots(figsize=(8, 4))
    ax.plot(xs, vals, marker="o", linestyle="-", label="|B| numerical")

    with np.errstate(divide="ignore", invalid="ignore"):
        analytic = analytic_wire_profile(xs, mu0, current, rc)
        ax.plot(xs, analytic, linestyle="--", label="|B| analytic")

    ax.set_xlabel("x [m]")
    ax.set_ylabel("|B| [T]")
    ax.set_title("Infinite wire validation line profile")
    ax.grid(True, which="both", linestyle="--", alpha=0.5)
    ax.legend()

    if save is not None:
        fig.savefig(save, dpi=200, bbox_inches="tight")
        print(f"Saved figure to {save}")

    plt.show()


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--csv",
        type=pathlib.Path,
        default=pathlib.Path("outputs/validation_wire_line.csv"),
        help="Path to the CSV line profile generated by the C++ test.",
    )
    parser.add_argument(
        "--current",
        type=float,
        default=10.0,
        help="Total current [A] used in the validation case.",
    )
    parser.add_argument(
        "--mu0",
        type=float,
        default=4.0e-7 * np.pi,
        help="Magnetic permeability of free space.",
    )
    parser.add_argument(
        "--core-radius",
        type=float,
        default=None,
        help="Wire core radius [m]; defaults to 3*dx inferred from the CSV grid.",
    )
    parser.add_argument(
        "--save",
        type=pathlib.Path,
        default=None,
        help="Optional output path to save the plot as PNG.",
    )
    args = parser.parse_args()

    if not args.csv.exists():
        raise SystemExit(f"CSV file not found: {args.csv} — run analytic_wire_test first.")

    xs, _ys, vals = read_profile(args.csv)

    dx = np.min(np.abs(np.diff(xs))) if xs.size > 1 else 0.0
    rc = args.core_radius if args.core_radius is not None else 3.0 * dx

    plot_profile(xs, vals, args.mu0, args.current, rc, args.save)


if __name__ == "__main__":
    main()
